# Generated by Django 3.1.6 on 2021-07-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='city',
            new_name='dsc_bairro',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='district',
            new_name='dsc_cidade',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='latitude',
            new_name='dsc_endereco',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='longitude',
            new_name='nom_estab',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='name',
            new_name='vlr_latitude',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='public_place',
            new_name='vlr_longitude',
        ),
    ]
