# Generated by Django 3.1.6 on 2021-07-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0002_auto_20210728_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='vlr_latitude',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='local',
            name='vlr_longitude',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
