# Generated by Django 3.1.6 on 2021-07-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0004_auto_20210729_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='vlr_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='vlr_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
