# Generated by Django 3.1.6 on 2021-08-01 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacinas', '0005_auto_20210730_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='vlr_latitude',
            field=models.CharField(default='C', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='vlr_longitude',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.IntegerField(blank=True, choices=[('A', 'Agendado'), ('C', 'Cancelado'), ('V', 'Vacinado')], default=1),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
