# Generated by Django 3.1.6 on 2021-08-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0007_auto_20210801_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduling',
            old_name='status',
            new_name='statu',
        ),
    ]
