# Generated by Django 3.1.6 on 2021-08-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0008_auto_20210801_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduling',
            old_name='statu',
            new_name='status',
        ),
    ]
